basePath: /
definitions:
  request.CardRequest:
    properties:
      card_number:
        type: string
      expiration_month:
        type: integer
      expiration_year:
        maximum: 9999
        minimum: 2021
        type: integer
    required:
    - card_number
    - expiration_month
    - expiration_year
    type: object
  response.CardError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.CardResponse:
    properties:
      error:
        $ref: '#/definitions/response.CardError'
      valid:
        type: boolean
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a sample server.
  title: API
  version: "1.0"
paths:
  /card/validate:
    post:
      consumes:
      - application/json
      description: Validates a credit card based on number, expiration month, and
        expiration year
      parameters:
      - description: Card details to validate
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/request.CardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Validation result
          schema:
            $ref: '#/definitions/response.CardResponse'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/response.CardResponse'
        "422":
          description: Parsing error
          schema:
            $ref: '#/definitions/response.CardResponse'
      summary: Validate a credit card
      tags:
      - Card
swagger: "2.0"
